name: PR GIF comment

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main
      - "*-release"

jobs:
  post-gif:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Post GIF
        uses: Heinux-Training/js-pr-comment-action@latest
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          giphy-api-key: ${{ secrets.GIPHY_KEY }}
